#!/bin/bash
full=`uname -a`

if [[ "$full" =~ .*aarch64.* ]]
then
  arch="arm64"
elif [[ "$full" =~ .*x86_64.* ]]
then
  arch="amd64"
else
  arch="unknown"
  echo "Unknown platform, building failed."
  exit 1
fi

if [ "$1" ]
then
  images=("$1")
else
  images=("alpine" "nginx" "node" "aria2")
fi

echo "================================"
echo "$full"
echo "Platform: `uname`/$arch"
echo "Building images:"
echo ${images[*]}
echo "================================"

for image in ${images[@]};
do
  echo
  echo "================================"
  echo "       Building $image..."
  cd $image; \
     bash build.sh $arch $image; \
     cd ..;
  echo "   $image building completed."
  echo "================================"
  echo
done

echo "================================"
echo "       Platform: $arch"
echo "      Building completed."
echo "================================"
